### ISSUE TITLE
AV-etiket billund

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#10]
> Billund har dette ønske til AV-etiketter.
> 
> Så vidt vi kan se, har vi ikke fået fx xbox på vores labels siden overgang til det nye bibliotekssystem. Vi vil gerne have oplysningen fra felt 245 *ø på AV-labels fremadrettet. Så må vi se, om det løser vores behov. Vi vil gerne have feltet placeret ved siden af felterne afdeling, opstilling og delopstilling.
> 
> 352438
> 352439
> 390855
> 390856
> 
> ref: DD@Billund.dk

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#14
