### ISSUE TITLE
Bindtitel på flerbindsværker, Ryesgade

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#11]
> Vi printer undertitel til hovedtitel og ikke bindtitel for UCL ved flerbindsværker. I dette tilfælde står bindtitel efter linjeskift i felt 245 *c.
> 
> ![image](https://user-images.githubusercontent.com/14905543/38423235-9e76759a-39ad-11e8-9dbe-0a8b90ef85e7.png)
> 
> Faust 52730112, skal hedde:
> 
> 81.6
> Litteratur med udsyn
> [Bind] 1: Migration, netlitteratur, vidnesbyrd
> 
> Vi printer:
> 81.6
> Litteratur med udsyn
> [Bind] 1: globale perspektiver i danskundervisningen
> 
> 81.6
> Litteratur med udsyn : globale perspektiver i danskundervisningen / forfattere: Anders Hedegaard
> 
> ID-NUMMER: 52789109
> DK5: 81.6
> 
> [Bind] 1 : Migration, netlitteratur, vidnesbyrd. - 245 sider
> ISBN-13: 9788779968462
> ID-NUMMER: 52730112
> 
> ref: elch@ucl.dk

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#13
