### ISSUE TITLE
Odder ønsker ikke cc50 trykt på spil og film-label

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#15]
Odder ønsker ikke cc50 trykt på spil og film-label. De ønsker stadig mærkaterne. Kundenumre 428650, 428654, 428642 og 428646. Ordrenr. 2530559.

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#9
