### ISSUE TITLE
Aarhus kundenr. 463582 og 463578 lydbøger børn og voksen skal konfigureres i Print Label

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#16]
Aarhus kundenr. 463582 og 463578 lydbøger børn og voksen skal konfigureres i Print Label. Ordreeks. 2456456 og 2456453.

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#8
