### ISSUE TITLE
Frederiksberg - 2465672

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#19]
Der kommer ingen oplysninger ud på alle varer på denne ordre: 2465672 - eller klassemærke for den sags skyld (det virker til at det er et generelt problem med serier). Rasmus har tjekket, og Frederiksberg har givet os oplysninger.

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#2
