### ISSUE TITLE
Aktiver UCC-kundenumre i Printlabel

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#2]
> Ran 27/02: UCC ønsker fremover ikke logo på etiketter og vil have printet "Københavns Professionshøjskole" i nederst på etikette. Dette skal ikke påvirke 558974 og 558977. Fx ordrenr. 2526347. Overordnet kn. 406482.
> 
> 
> Det ser ud til, at 609140 og 609122 mangler at blive aktiveret i printlabel.,
> 

Vil du gøre sådan, at de fremover får printet cc10 (filial) øverst på label før opstilling (cc30)?

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#22
