### ISSUE TITLE
Svendborg - problemer med "The"

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#21]
Hver gang der er en varer der har en titel med “The” i det, så kan den ikke forstå den der lille streg der kommer under det første bogstav som de fleste biblioteker har (det er stregen der indikerer at varens titel fx. I det her tilfælde er, The Dwarves - ergo, Dwarves og ikke “The”). Problemet opstår selvfølgelig også på disclabel.

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#4
