### ISSUE TITLE
Greve opstilling + 666 *o formbetegnelse

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#23]
Greve ønsker følgende opstilling øverst på AV-labels (Placeres venstre hjørne.)
Cc10, cc20 og cc40. Fx faust. 53182844 på ordrenr. 2449574. Kundenummer 439446.
Det ser ud til, at vi på nuværende tidspunkt printer "666 *o formbetegnelse"? Dette skal ikke med.

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#1
