### ISSUE TITLE
Vallensbæk rykker for deres film

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#3]
> Disclabels er forkert. På film mangler “målgruppe” øverst, hvilket gør at hele teksten forskydes fx ordre: 2514428 og ved spil er det også forskudt.
> 
> ref: ago@vallensbaek.dk
> 
> jrishoj commented 20 days ago
> Så vidt jeg kan se kommer alt med på disklabels (fx på ordre 2514428)
> Jeg skal lige vide hvad er "målgruppe"?
>   
> Rasmusah commented 18 days ago • 
> Der menes delopstilling, cc40. Vi har lavet en test, og delopstilling bliver ikke printet.
> Det gælder både børn og voksen.
> 
> 
> jrishoj commented a day ago
> Rette på begge labels. @Rasmusah Få godkendelse af kunden før vi kører løs.
> 
>   
> Rasmusah commented a day ago
> Skriver til dem.
> 
Rasmusah commented 23 hours ago
De savner et V for voksen. Jeg formoder, at de også ønsker B for børn.

![image](https://user-images.githubusercontent.com/14905543/38421697-52cacaec-39a8-11e8-8c34-69391191354b.png)

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#21
