### ISSUE TITLE
Klargjort AV til Silkeborg

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#4]
> Rasmusah commented 28 days ago
> Silkeborg vil fremover gerne have klargjort AV og har oprettet disse kundenumre. De skal aktiveres i printlabel.
> 
> Film - Børn - Klargjort 610577
> Film - Voksen - Klargjort 610580
> Lydbog - Børn - Klargjort 610583
> Lydbog - Voksen - Klargjort 610586
> Spil - Børn - Klargjort 610592
> 
> De skal selv sende MP3-mærkater til os.
> 
> [Rasmus (1).pdf](https://github.com/AudioVisionaryMusic/AV-labels/files/1883975/Rasmus.1.pdf)
> 
> ref: jb@Silkeborgbib.dk
>    
> 
> jrishoj commented a day ago
> @Rasmusah
> Til Silkeborg har vi hidtil kun leveret AV-musik klargjort. I øvrigt på kundenummer 267012 (som åbenbart nu er deres overordnede kundenummer).
> Skal Film og Spil fremover klargøres, skal vi vide
> 
> hvad de ønsker skal medtages på etiketter
> hvor oplysningerne skal stå
> Grafik-fil for logo (hvis det skal på)
> både for den bibliografiske og skrive-etiketten.
> Få gerne eksempler på etiketter / klargjorte Film og Spil fra Silkeborg.
> Vi laver derefter prøver til deres godkendelse.
> 
>   

Rasmusah commented a day ago
De er link til etikette i den oprindelige kommentar.

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#20
