### ISSUE TITLE
Klargøring film Varde

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#5]
Sig til, hvis der er noget der er uklart.

> Hej Gitte.
> 
> Pirates of the Carribean – Salazar’s Revenge
> Vi modtager denne opstilling i jeres bestilling:
> 
> va vo DVD Lån 7 d 7
> 
> Det ser ud til, at vi kunne imødekomme jeres ønske ved kun at trykke delopstillingen - "Lån 7 d" (cc40). Jeg ikke ikke helt gennemskue hvor "(DVD)" efter titel bliver hentet fra, men jeg er enig i, at det er overflødigt og bør fjernes. Så står der kun "1 dvd-video", hvilket virker som den mest "korrekt" medie-angivelse. Hvis "(DVD)" efter titel fjernes, ville der også være mere plads til undertitel.
> 
> Game of Thrones
> Disc og episodenummer ser ud til at kunne kan trækkes fra 245 *g - numerisk eller alfabetisk betegnelse for bind (i bindpost). Det vil vi gøre fremover.
> 
> Jeg vender tilbage, når det er rettet.
> 
> Rasmus, iMusic.
> 
> Den 07-03-2018 kl. 14:58 skrev salg:
> 
> Hej,
> 
> Vi har et lille stykke tid lagt mærke til, at specielt vores filmlabels har ret mangelfulde oplysninger. Vi håber, der kan rettes op på det.
> 
> Her er et par eksempler:
> 
> Pirates of the Carribean – Salazar’s Revenge:
> 
> Undertitlen står hverken på bagsidelabel eller ryglabel. Det mangler vi ret meget.
> 
> Derimod er det slet ikke nødvendigt at skrive, om det er en DVD eller Bluray (i dette tilfælde står det hele 3 steder på samme label) Vi tænker i hvert fald, at betegnelsen kan fjernes i titellinjen.
> 
> Vi kunne også tænke os, at 7 tallet ikke står helt alene, men at der kommer til at stå det samme som på vores delopstilling: Lån 7 d (alternativt: 7 dage)
> 
> Game of Thrones:
> 
> Her mangler vi disc-nummer (evt. episode nummer) og sæson nummer. Det står fint inde på selve discen.
> 
> Derimod er det slet ikke nødvendigt at skrive, om det er en DVD eller Bluray (i dette tilfælde står det hele 3 steder på samme label) Vi tænker i hvert fald, at betegnelsen kan fjernes i titellinjen.
> 
> Vi kunne også tænke os, at 7 tallet ikke står helt alene, men at der kommer til at stå det samme som på vores delopstilling: Lån 7 d (alternativt: 7 dage)
> 
> Venlig hilsen
> 
> Gitte Gade
> Administrativ medarbejder
> 
> T: 76946904
> E: giga@vardebib.dk

![image](https://user-images.githubusercontent.com/14905543/38422042-a7497e0a-39a9-11e8-9779-38222ee391db.png)
![image](https://user-images.githubusercontent.com/14905543/38422051-add85cb4-39a9-11e8-9ca9-f2185ac5827b.png)

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#19
