### ISSUE TITLE
Alfabetisk underdeling for biplacering trykkes på etiket, når hovedplacering mangler - Roskilde

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#6]
Vi trykker alfabetisk underdeling for biplacering, når alfabetisk underdeling for hovedplacering mangler. Det skal vi ikke. Det gælder for alle kunder. Alfabetisk underdeling er det der står efter klassemærket.

![image](https://user-images.githubusercontent.com/14905543/38422133-ec38e44c-39a9-11e8-887a-6e613a777b95.png)

Faust 53389120 bestilt på 422595, ordrenr. 2476595.

DK5-klassemærke, inkl. alfabetisk underdeling
652 *m	opstillings- og hovedplacering	79.86

DK5-klassemærke, inkl. alfabetisk underdeling
652 *p	biplacering	99.4
652 *a	efternavn/navn/korporationsnavn som alfabetisk underdeling	Peterson
652 *h	fornavne	Ronnie

Se også denne: #2130

Spørg hvis der er noget, der er uklart.

ref: helensv@roskilde.dk

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#18
