### ISSUE TITLE
Etiket Solrød

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#7]
> Solrød vil gå over til automotagelse (!)
> 
> https://www.imusic.dk/page/customer?id=435490
> Materialenummer skal tilføjes på deres etiketter, både som tal og som stregkode.
> Faustnummer fjernes som stregkode og beholdes som tal.
> 
> Når det er klar: RFID chip tilføjes, med 726900.
> 
>  @crishoj crishoj self-assigned this on 13 Feb
>   
> crishoj commented on 13 Feb
> Fagre ny verden!
> 
>   
> crishoj commented on 13 Feb
> Hmm... den nuværende stregkode er faktisk materialenummer(!).
> 
> Jeg nøjes med at tilføje materialenummer som tal.
> 
>   
> crishoj commented on 13 Feb
> Jeg har aktiveret RFID for Solrøds klargjorte kundenumre.
> 
> Indtastning af modtageradresse til ship notice mangler.
> 
> @jrishoj / @LoneHoppe — skal arbejdsgangen for AV-klargøring tilpasses?
>   
> serenabo commented 9 days ago
> @Rasmusah vil du høre Solrød af vdr. klargøring af film og spil: skal de til at have RFID chip?
> 
>   
> Rasmusah commented 3 days ago
> Ja, jeg skriver til dem.
> 

  
Rasmusah commented 2 days ago
De ønsker også RFID på spil og film. @fhwac retter du deres etiketter til? Kundenumre 436426, 436422, 436434 og 436430.

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#17
