### ISSUE TITLE
Tønder - etiket til lydbøger

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#8]
> Er ikke lavet. @jrishoj
> 
> https://www.imusic.dk/page/customer?id=515249
> 
> Brug etikette for spil / film. Klargøres som spil / film, men i egen kassette
> 
>  @serenabo serenabo assigned jrishoj on 28 Nov 2017
>   
> serenabo commented on 28 Nov 2017
> Sender nu disse uklargjort
> 
> ![image](https://user-images.githubusercontent.com/14905543/38422409-efce109a-39aa-11e8-8134-24c8b1008c7a.png)
> 
> 
>   
> serenabo commented 9 days ago
> Kan denne lukkes @Rasmusah ?

  
Rasmusah commented 3 days ago • 
Nej, den er stadig ikke lavet, så vidt jeg kan se.

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#16
