### ISSUE TITLE
99.4 UCL

### ISSUE THREAD

**Issue by Rasmusah** [AudioVisionaryMusic/AV-labels#9]
![image](https://user-images.githubusercontent.com/14905543/38422588-9b253784-39ab-11e8-94ce-06971c3d3169.png)

> Hvis klassemærket er 99.4 skal der altid alfabetisk underdeling med efter klassemærket?
> Skal forfatter stadig stå på sædvanlig plads?
> 
> Ja.
> 
> Roskilde oplyser, at de kun får forfatterefternavn på etiket som alfabetisk underdeling. Fornavn skal også med.
> fx mat nr. 5169094960
> 
> image
> 
> image
> 
> Skal være:
> 99.4 Matthesen, Anders
> 
> @jrishoj 
> 
> @jrishoj — FYI, i flow er det implementeret ved at alle materialer med klassemærke 99.* og 72.* får 652 a og h (med komma imellem), samt evt. 652 e og f som "alfabetisk underinddeling".
> 
![image](https://user-images.githubusercontent.com/14905543/38422677-ee76ed6a-39ab-11e8-88c7-e715505c110f.png)
> 
> De har skrevet igen med et nyt eksempel - hvad jeg kan melde tilbage @jrishoj ?

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/R18-Utils#15
